import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Footer from "../../components/Footer";
import Header from "../../components/Header";
import styles from "../../styles/Work.corrections.module.scss";

const Work: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Etap poprawek | Delta Storm</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <main className={styles.main}>
                <div className={styles.content}>
                    <h2>Etap poprawek</h2>
                    <p>
                        Prezentacja całego projektu oraz jeżeli projekt nie
                        spełnia wymogów umowy lub design został dodany warunkowo
                        zostają naniesione niezbędne poprawki.
                    </p>
                </div>
                <div className={styles.image}>
                    <div className={styles.imageWrapper}>
                        <Image
                            src="/images/work/corrections/image.svg"
                            layout="fill"
                            alt="Zdjęcie etapu poprawek"
                        />
                    </div>
                </div>
            </main>
            <nav className={styles.navButtons}>
                <Link href="/work/production">{`< Poprzedni etap`}</Link>
                <Link href="/work/final">{`Następny etap >`}</Link>
            </nav>
            <Footer />
        </div>
    );
};

export default Work;
