import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Footer from "../../components/Footer";
import Header from "../../components/Header";
import styles from "../../styles/Work.final.module.scss";

const Work: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Etap końcowy | Delta Storm</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <main className={styles.main}>
                <div className={styles.content}>
                    <h2>Etap końcowy</h2>
                    <p>
                        Oficjalne przekazanie pełnej strony wraz z raportem
                        zawierającym wszystkie informacje co zostało zrobione na
                        rzecz projektu.
                    </p>
                </div>
                <div className={styles.image}>
                    <div className={styles.imageWrapper}>
                        <Image
                            src="/images/work/final/image.svg"
                            layout="fill"
                            alt="Zdjęcie etapu końcowego"
                        />
                    </div>
                </div>
            </main>
            <nav className={styles.navButtons}>
                <Link href="/work/corrections">{`< Poprzedni etap`}</Link>
                {/* <Link href="/work/time">{`Następny etap >`}</Link> */}
            </nav>
            <Footer />
        </div>
    );
};

export default Work;
