import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { FormEvent, useState } from "react";
import Footer from "../components/Footer";
import Header from "../components/Header";
import styles from "../styles/Contact.module.scss";

const Home: NextPage = () => {
    const [isEmailSend, setIsEmailSend] = useState(false);
    const [email, setEmail] = useState("");
    const [subject, setSubject] = useState("");
    const [content, setContent] = useState("");

    const handleSubmit = async (e: FormEvent<HTMLElement>) => {
        const data = { email, subject, content };
        e.preventDefault();
        const result = await fetch("https://deltastorm.pl/api/messages", {
            headers: { "Content-Type": "application/json" },
            method: "POST",
            body: JSON.stringify(data),
        });
        const response = await result.json();
        console.log("response :>> ", response);
        if (response.status === 200) {
            setIsEmailSend(true);
        }
    };
    return (
        <div className={styles.container}>
            <Head>
                <title>Kontakt | Delta Storm</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <main className={styles.main}>
                {!isEmailSend ? (
                    <div className={styles.formWrapper}>
                        <h2>Formularz kontaktowy</h2>
                        <form action="#" method="post" onSubmit={handleSubmit}>
                            <input
                                type="text"
                                name="subject"
                                id="subject"
                                placeholder="Temat"
                                required
                                value={subject}
                                onChange={(e) => setSubject(e.target.value)}
                            />
                            <input
                                type="email"
                                name="email"
                                id="email"
                                placeholder="E-mail"
                                required
                                value={email}
                                onChange={(e) => setEmail(e.target.value)}
                            />
                            <textarea
                                required
                                name="message"
                                id="message"
                                placeholder="Wiadomość..."
                                value={content}
                                onChange={(e) => setContent(e.target.value)}
                            />
                            <button type="submit">Wyślij</button>
                        </form>
                    </div>
                ) : (
                    <div className={styles.sendMail}>
                        <p>Twoja wiadomosć została wysłana</p>
                        <p>Skontaktujemy się z Tobą jak najszybciej!</p>
                        <div className={styles.imageWrapper}>
                            <Image
                                src="/images/contact/sended.svg"
                                layout="fill"
                                alt="Wysłana wiadomość"
                            />
                        </div>
                    </div>
                )}
                <div className={styles.contactWrapper}>
                    <div className={styles.contactElement}>
                        <div className={styles.imageWrapper}>
                            <Image
                                src="/images/contact/tel.svg"
                                layout="fill"
                                alt="Zdjęcie kontktu"
                            />
                        </div>
                        <a href="tel:+48572868190">572-868-190</a>
                    </div>
                    <div className={styles.contactElement}>
                        <div className={styles.imageWrapper}>
                            <Image
                                src="/images/contact/mail.svg"
                                layout="fill"
                                alt="Zdjęcie kontktu"
                            />
                        </div>
                        <a href="mailto:kontakt@deltastorm.pl">
                            kontakt@deltastorm
                        </a>
                    </div>
                    <div className={styles.contactElement}>
                        <div className={styles.imageWrapper}>
                            <Image
                                src="/images/contact/adress.svg"
                                layout="fill"
                                alt="Zdjęcie kontktu"
                            />
                        </div>
                        <p>
                            <span>Trębowiec Mały 9</span>
                            <span>27-220 Mirzec</span>
                        </p>
                    </div>
                </div>
            </main>
            <Footer />
        </div>
    );
};

export default Home;
