import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Footer from "../components/Footer";
import Header from "../components/Header";
import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Home | Delta Storm</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <main className={styles.main}>
                <div className={styles.content}>
                    <h2>Jesteśmy</h2>
                    <h1>Delta Storm</h1>
                    <p>
                        Jako Delta Storm zajmujemy się kompleksowym budowaniem
                        witryn internetowych zgodnie z panującymi trendami.
                        Wspieramy naszych klientów przy budowie biznesu
                        internetowego. Nasi Designerzy pomogą Wam nie tylko
                        przygotować niesamowitą stronę internetową ale zapewnią
                        wsparcie na każdym etapie współpracy.
                    </p>
                </div>
                <div className={styles.image}>
                    <div className={styles.imageWrapper}>
                        <Image
                            src="/images/home/image.png"
                            layout="fill"
                            alt="Zdjęcie laptopa"
                        />
                    </div>
                </div>
            </main>
            <Footer />
        </div>
    );
};

export default Home;
