import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import Footer from "../components/Footer";
import Header from "../components/Header";
import styles from "../styles/Projects.module.scss";

interface ProjectI {
    id: number;
    title: string;
    tags: string[];
    content: string;
    img: string;
    live: string;
}

const Projects: NextPage<{ projects: ProjectI[] }> = ({ projects }) => {
    const router = useRouter();
    const projectsList = projects
        .slice(0, 4)
        .map((project) => (
            <ProjectElement project={project} key={project.id} />
        ));
    return (
        <div className={styles.container}>
            <Head>
                <title>Portfolio | Delta Storm</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <main className={styles.main}>
                <h2>Portfolio</h2>
                <div className={styles.projectsWrapper}>{projectsList}</div>
            </main>
            <nav className={styles.navButtons}>
                <button className={styles.navButton}>{`<`}</button>
                <button
                    className={`${styles.navButton} ${styles.active}`}
                    onClick={() => router.push("/projects/page/1")}
                >{`>`}</button>
            </nav>
            <Footer />
        </div>
    );
};

const ProjectElement: NextPage<{ project: ProjectI }> = ({ project }) => {
    const { id, title, tags, img, live } = project;
    const tagList = tags.map((tag, i) => (
        <div className={styles.tag} key={i}>
            {tag}
        </div>
    ));
    return (
        <div className={styles.projectWrapper}>
            <div className={styles.content}>
                <h3>
                    <a href={live} target="_blank" rel="noopener noreferrer">
                        {title}
                    </a>
                </h3>
                <h4>Technologie</h4>
                <div className={styles.tags}>{tagList}</div>
            </div>
            <div className={styles.imageWrapper}>
                <Image
                    src={`${img}`}
                    layout="fill"
                    alt="Zdjęcie projektu"
                ></Image>
            </div>
        </div>
    );
};

export const getServerSideProps: GetServerSideProps<{
    projects: ProjectI[];
}> = async () => {
    const response = await fetch("https://deltastorm.pl/data/portfolio.json");
    const projects = await response.json();
    return { props: { projects } };
};

export default Projects;
